name: Build and push Docker image

on:
  workflow_dispatch:
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worker-auth:${{ steps.vars.outputs.short_sha }} 

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/worker-auth:${{ steps.vars.outputs.short_sha }} 
